# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# basic pipeline with environment variable 
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - checkout
     - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - checkout
     - run: npm run test
  Analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - checkout
     - run: npm audit

# Use a package of configuration called an orb.

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  First_CI:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

